# Generated by Django 4.0.4 on 2022-06-08 08:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('content', ckeditor.fields.RichTextField()),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('content_kk', ckeditor.fields.RichTextField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.categorycontent')),
            ],
            options={
                'verbose_name': 'Контент с категориями',
                'verbose_name_plural': 'Контент с категориями',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaslihatSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='solutions/', verbose_name='Файл')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.categorycontent')),
            ],
            options={
                'verbose_name': 'Файловый контент с категорией',
                'verbose_name_plural': 'Решения маслихата',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
