# Generated by Django 4.0.4 on 2022-06-01 12:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solitions',
            name='content_kk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='solitions',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='solitions',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='solitions',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
