# Generated by Django 4.0.4 on 2022-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_solitions_content_kk_solitions_content_ru_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solitions',
            new_name='Solutions',
        ),
        migrations.AddField(
            model_name='maslihatsolution',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='maslihatsolution',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
