# Generated by Django 4.0.4 on 2022-06-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_categoryfiles_alter_categorycontent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycontent',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='categorycontent',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='categoryfiles',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='categoryfiles',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория'),
        ),
    ]
