# Generated by Django 4.0.4 on 2022-06-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='position',
        ),
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_position', to='employee.position', verbose_name='Должность'),
        ),
    ]
