# Generated by Django 4.0.4 on 2022-06-01 12:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='awards_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Государственные награды, почетные звания'),
        ),
        migrations.AddField(
            model_name='employees',
            name='awards_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Государственные награды, почетные звания'),
        ),
        migrations.AddField(
            model_name='employees',
            name='birth_place_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='employees',
            name='birth_place_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='employees',
            name='content_kk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='edu_degree_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученое звание'),
        ),
        migrations.AddField(
            model_name='employees',
            name='edu_degree_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученое звание'),
        ),
        migrations.AddField(
            model_name='employees',
            name='edu_end_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Окончил в'),
        ),
        migrations.AddField(
            model_name='employees',
            name='edu_end_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Окончил в'),
        ),
        migrations.AddField(
            model_name='employees',
            name='edu_place_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Образование в'),
        ),
        migrations.AddField(
            model_name='employees',
            name='edu_place_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Образование в'),
        ),
        migrations.AddField(
            model_name='employees',
            name='edu_speciality_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность по оброзованию'),
        ),
        migrations.AddField(
            model_name='employees',
            name='edu_speciality_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность по оброзованию'),
        ),
        migrations.AddField(
            model_name='employees',
            name='party_affiliation_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Партийная принадлежность'),
        ),
        migrations.AddField(
            model_name='employees',
            name='party_affiliation_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Партийная принадлежность'),
        ),
        migrations.AddField(
            model_name='pastwork',
            name='position_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='pastwork',
            name='position_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='pastwork',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы'),
        ),
    ]
