# Generated by Django 4.0.4 on 2022-06-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employees_awards_kk_employees_awards_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastwork',
            options={'managed': True, 'verbose_name': 'Последнее место работы', 'verbose_name_plural': 'Последнее место работы'},
        ),
        migrations.AlterModelTable(
            name='pastwork',
            table='',
        ),
    ]
