# Generated by Django 4.0.4 on 2022-06-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_pastwork_options_alter_pastwork_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Категория')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
