# Generated by Django 4.0.4 on 2022-06-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория'),
        ),
    ]
