# Generated by Django 4.0.4 on 2022-06-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город или район')),
                ('place', models.TextField(verbose_name='Расписание, место')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_timetable', to='employee.employees', verbose_name='Депутат')),
            ],
            options={
                'verbose_name': 'График приема граждан',
                'verbose_name_plural': 'График приема граждан',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
