# Generated by Django 4.0.4 on 2022-06-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employees_category_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_category', to='employee.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
