# Generated by Django 4.0.4 on 2022-06-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employees_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employees', verbose_name='Депутат'),
        ),
    ]
