# Generated by Django 4.0.4 on 2022-05-25 12:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='Дата')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='anons/', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='Дата')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='news/', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
