# Generated by Django 4.0.4 on 2022-06-07 13:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField()),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('content_kk', ckeditor.fields.RichTextField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('image', models.ImageField(upload_to='anons/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Анонсы',
                'verbose_name_plural': 'Анонсы',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField()),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('content_kk', ckeditor.fields.RichTextField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Какой квартал')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Какой квартал')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Какой квартал')),
            ],
            options={
                'verbose_name': 'Квартал',
                'verbose_name_plural': 'Кварталы',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('desc_ru', models.TextField(null=True, verbose_name='Описание')),
                ('desc_kk', models.TextField(null=True, verbose_name='Описание')),
                ('commission', models.TextField(verbose_name='Коммисия')),
                ('commission_ru', models.TextField(null=True, verbose_name='Коммисия')),
                ('commission_kk', models.TextField(null=True, verbose_name='Коммисия')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_section', to='main.section')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'План',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
