# Generated by Django 4.0.4 on 2022-05-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anons',
            options={'managed': True, 'verbose_name': 'Анонсы', 'verbose_name_plural': 'Анонсы'},
        ),
        migrations.AlterField(
            model_name='anons',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
