# Generated by Django 4.0.4 on 2022-06-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_anons_date_alter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_fio', models.CharField(max_length=255, verbose_name='Кому')),
                ('from_fio', models.CharField(max_length=255, verbose_name='От кого')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИИН')),
                ('email', models.EmailField(blank=True, max_length=12, null=True, verbose_name='Почта')),
                ('content', models.TextField(verbose_name='Текст сообщения')),
                ('file', models.FileField(blank=True, null=True, upload_to='message/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Сұрақтар',
                'verbose_name_plural': 'Сұрақтар',
            },
        ),
    ]
