# Generated by Django 4.0.4 on 2022-05-26 09:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_anons_options_alter_anons_date_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anons',
            name='content_kk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='anons',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='anons',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='anons',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_kk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
