# Generated by Django 4.0.4 on 2022-06-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_messsage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messsage',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта'),
        ),
    ]
