# Generated by Django 4.0.4 on 2022-06-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_anons_date_alter_anons_image_alter_anons_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Какой квартал')),
            ],
            options={
                'verbose_name': 'Квартал',
                'verbose_name_plural': 'Кварталы',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('commission', models.TextField(verbose_name='Коммисия')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_section', to='main.section')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'План',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
