# Generated by Django 4.0.4 on 2022-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_section_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='commission_kk',
            field=models.TextField(null=True, verbose_name='Коммисия'),
        ),
        migrations.AddField(
            model_name='plan',
            name='commission_ru',
            field=models.TextField(null=True, verbose_name='Коммисия'),
        ),
        migrations.AddField(
            model_name='plan',
            name='desc_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='plan',
            name='desc_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='section',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Какой квартал'),
        ),
        migrations.AddField(
            model_name='section',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Какой квартал'),
        ),
    ]
